from pathlib import Path

runtime = Path('public/captains-log-dashboard/dashboard-runtime-fixes.js')
text = runtime.read_text()

old = """  function isSocialSource(source){\n    return Boolean(source&&SOCIAL_SOURCE_IDS.has(source.id));\n  }\n"""
new = """  function isSocialSource(source){\n    return Boolean(source&&SOCIAL_SOURCE_IDS.has(source.id));\n  }\n\n  function isPermitSource(source){\n    if(!source)return false;\n    const id=String(source.id||'').toLowerCase();\n    const label=String(source.label||'').toLowerCase();\n    return id==='permit_offices'||id==='permit_radar'||id.includes('permit')||label==='permit offices';\n  }\n"""
if old not in text:
    raise SystemExit('isSocialSource anchor not found')
text = text.replace(old, new, 1)

old = """  function renderNetworkTaxonomy(map){\n    if(!map||!Array.isArray(map.sources))return;\n    const lanes=ensureOutputLanes();\n    const totals=socialTotals(map);\n    const buyerNode=lanes?.querySelector('[data-signal-buyer-total]');\n    const replyNode=lanes?.querySelector('[data-signal-reply-total]');\n    if(buyerNode)buyerNode.textContent=formatCount(totals.buyers);\n    if(replyNode)replyNode.textContent=formatCount(totals.replies);\n\n    const producingNode=document.querySelector('[data-phase1-producing-sources]');\n"""
new = """  function renderNetworkTaxonomy(map){\n    if(!map||!Array.isArray(map.sources))return;\n    const lanes=ensureOutputLanes();\n    const totals=socialTotals(map);\n    const buyerNode=lanes?.querySelector('[data-signal-buyer-total]');\n    const replyNode=lanes?.querySelector('[data-signal-reply-total]');\n    const buyerLane=buyerNode?.closest('.signal-output-lane');\n    const replyLane=replyNode?.closest('.signal-output-lane');\n    const outcomeRoot=document.querySelector('.map-outcomes');\n    const outputLabel=outcomeRoot?.querySelector('.map-outcomes-label');\n    const outputHeading=outcomeRoot?.querySelector('#mapDestinationHeading');\n    const source=selectedSource();\n\n    if(isPermitSource(source)){\n      if(outputLabel)outputLabel.textContent='Permit Outputs';\n      if(outputHeading)outputHeading.textContent='Permit Projects';\n      const buyerLabel=buyerLane?.querySelector('span');\n      const buyerCaption=buyerLane?.querySelector('small');\n      const replyLabel=replyLane?.querySelector('span');\n      const replyCaption=replyLane?.querySelector('small');\n      if(buyerLabel)buyerLabel.textContent='Qualified Projects';\n      if(buyerCaption)buyerCaption.textContent='Permit Opportunities';\n      if(replyLabel)replyLabel.textContent='Working Now';\n      if(replyCaption)replyCaption.textContent='Active Permit Projects';\n      if(buyerNode)buyerNode.textContent=formatCount(source.surfaced);\n      if(replyNode)replyNode.textContent=formatCount(source.working);\n      if(outcomeRoot)outcomeRoot.dataset.outputTaxonomy='permit';\n    }else{\n      if(outputLabel)outputLabel.textContent='Social Outputs';\n      if(outputHeading)outputHeading.textContent='Leads + Replies';\n      const buyerLabel=buyerLane?.querySelector('span');\n      const buyerCaption=buyerLane?.querySelector('small');\n      const replyLabel=replyLane?.querySelector('span');\n      const replyCaption=replyLane?.querySelector('small');\n      if(buyerLabel)buyerLabel.textContent='Leads';\n      if(buyerCaption)buyerCaption.textContent='Buyer Opportunities';\n      if(replyLabel)replyLabel.textContent='Replies';\n      if(replyCaption)replyCaption.textContent='Reply Opportunities';\n      if(buyerNode)buyerNode.textContent=formatCount(totals.buyers);\n      if(replyNode)replyNode.textContent=formatCount(totals.replies);\n      if(outcomeRoot)outcomeRoot.dataset.outputTaxonomy='social';\n    }\n\n    const producingNode=document.querySelector('[data-phase1-producing-sources]');\n"""
if old not in text:
    raise SystemExit('renderNetworkTaxonomy anchor not found')
text = text.replace(old, new, 1)
runtime.write_text(text)

test = Path('tests/signal-permit-output-taxonomy.test.mjs')
test.write_text("""import test from 'node:test';\nimport assert from 'node:assert/strict';\nimport fs from 'node:fs';\n\nconst source = fs.readFileSync('public/captains-log-dashboard/dashboard-runtime-fixes.js', 'utf8');\n\ntest('Permit Offices uses project terminology instead of social lead/reply terminology', () => {\n  const start = source.indexOf('  function renderNetworkTaxonomy(map){');\n  const end = source.indexOf('\\n  function renderSourceCards(map){', start);\n  assert.ok(start >= 0 && end > start, 'network taxonomy renderer must remain discoverable');\n  const block = source.slice(start, end);\n  assert.match(block, /isPermitSource\\(source\\)/);\n  assert.match(block, /textContent='Permit Outputs'/);\n  assert.match(block, /textContent='Qualified Projects'/);\n  assert.match(block, /textContent='Permit Opportunities'/);\n  assert.match(block, /textContent='Working Now'/);\n  assert.match(block, /textContent='Active Permit Projects'/);\n  assert.match(block, /buyerNode\\.textContent=formatCount\\(source\\.surfaced\\)/);\n  assert.match(block, /replyNode\\.textContent=formatCount\\(source\\.working\\)/);\n});\n\ntest('social output copy is restored for non-permit selections', () => {\n  const start = source.indexOf('  function renderNetworkTaxonomy(map){');\n  const end = source.indexOf('\\n  function renderSourceCards(map){', start);\n  const block = source.slice(start, end);\n  assert.match(block, /textContent='Social Outputs'/);\n  assert.match(block, /textContent='Leads'/);\n  assert.match(block, /textContent='Replies'/);\n  assert.match(block, /dataset\\.outputTaxonomy='social'/);\n});\n""")
