-- RETIRED DRAFT — DO NOT RUN.
--
-- This early migration was superseded after the live Supabase schema was reviewed.
-- The final migration is intentionally supplied as SUPABASE_COMPANY_IDENTITY_V1_FINAL.sql
-- with the Client Compass v1.0.9.97 / Captain's Log V846 / Mobile V260 rollout.
--
-- The final migration is ambiguity-safe: Supabase owns the UUID, exact durable
-- external-ID mappings win, exact normalized names are reused only when unique,
-- and fuzzy matching is never allowed to establish permanent company identity.
--
-- Keeping this file as an explicit tombstone prevents the earlier draft from
-- being copied into the Supabase SQL Editor by mistake.
