import type { Project } from "@/lib/projects/types";
import { HIPAA_QUESTIONS } from "./questions";
import { HIPAA_DISCLAIMER, scoreHipaaAssessment } from "./engine";

function escapeHtml(value: string): string {
  return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);
}
function safeFileName(value: string): string { return value.trim().replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase() || "hipaa-readiness-appendix"; }
function responseLabel(value: string): string {
  return value === "not-applicable" ? "Does not apply" : value === "not-yet-assessed" ? "Not sure / unanswered" : value.charAt(0).toUpperCase() + value.slice(1);
}

export function hipaaAppendixHtml(project: Project): string {
  const score = scoreHipaaAssessment(project.hipaa);
  const rows = HIPAA_QUESTIONS.map((question) => {
    const answer = project.hipaa.answers.find((item) => item.questionId === question.id);
    if (!answer) return "";
    const evidence = [answer.evidenceSource, answer.internalNotes, answer.evidenceAttachment?.name].filter(Boolean).join(" · ");
    return `<tr><td><strong>${escapeHtml(question.id)}</strong><small>${escapeHtml(question.ownership.replace("advantage-prefill", "Advantage prefill"))}</small></td><td><strong>${escapeHtml(question.title)}</strong><small>${escapeHtml(question.question)}</small></td><td><span class="response response-${answer.response}">${escapeHtml(responseLabel(answer.response))}</span></td><td>${escapeHtml(evidence || "Not yet verified")}</td><td>${escapeHtml(answer.clientVisibleObservation || "—")}</td><td>${escapeHtml(answer.recommendedAction || "—")}</td></tr>`;
  }).join("");
  const period = [project.hipaa.reportingPeriod.start, project.hipaa.reportingPeriod.end].filter(Boolean).join(" to ") || "Reporting period not selected";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(project.client.name)} HIPAA Security Readiness Appendix</title><style>
  :root{--navy:#071a34;--blue:#1766de;--ink:#0b1830;--muted:#66758a;--line:#dfe6ef;--bg:#eef2f6;--green:#15977f;--yellow:#b67d13;--red:#c95138}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{width:min(1320px,calc(100% - 32px));margin:auto;padding:28px 0 80px}.top{display:flex;justify-content:space-between;color:#748197;font-size:12px;padding:14px 0}.hero{border-radius:28px;padding:46px;background:linear-gradient(130deg,#06172f,#0b336c 60%,#1766de);color:white}.hero h1{font-size:clamp(38px,6vw,68px);line-height:1;margin:10px 0 16px}.hero p{max-width:920px;color:#dceaffc9;line-height:1.65}.score{display:grid;grid-template-columns:1.4fr repeat(4,1fr);gap:12px;margin:16px 0 28px}.score article{background:white;border:1px solid var(--line);border-radius:18px;padding:20px}.score strong{display:block;font-size:32px}.score span{display:block;margin-top:5px;font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);font-weight:800}.summary{padding:17px 20px;border-radius:16px;background:#fff;border:1px solid var(--line);margin-bottom:18px;color:var(--muted);line-height:1.55}.table-wrap{overflow:auto;background:white;border:1px solid var(--line);border-radius:20px}.table{border-collapse:collapse;width:100%;min-width:1220px}.table th,.table td{text-align:left;vertical-align:top;border-bottom:1px solid var(--line);padding:14px;font-size:11px;line-height:1.45}.table th{position:sticky;top:0;background:#f2f5f9;color:#6f7d91;text-transform:uppercase;letter-spacing:.07em;font-size:9px}.table td strong,.table td small{display:block}.table td small{margin-top:4px;color:var(--muted)}.response{display:inline-flex;border-radius:999px;padding:6px 9px;font-size:9px;font-weight:850;text-transform:uppercase;letter-spacing:.05em;background:#edf1f6}.response-yes{background:#dbf5ee;color:#087d69}.response-partially{background:#fff0cf;color:#93620a}.response-no{background:#ffe2dc;color:#a7442c}.response-not-yet-assessed{background:#e9edf2;color:#5f6d7d}.disclaimer{margin-top:24px;padding:18px;border-left:4px solid var(--blue);background:white;color:var(--muted);line-height:1.6}.footer{display:flex;justify-content:space-between;margin-top:28px;padding-top:20px;border-top:1px solid #ccd7e4;color:#748197;font-size:11px}.toolbar{position:fixed;right:20px;bottom:20px}.toolbar button{border:0;border-radius:13px;padding:13px 17px;background:var(--navy);color:white;font-weight:800;cursor:pointer}@media(max-width:800px){.score{grid-template-columns:1fr 1fr}.hero{padding:30px}.footer{flex-direction:column;gap:6px}}@media print{body{background:white}main{width:100%;padding:0}.toolbar{display:none}.table-wrap{overflow:visible}.table th{position:static}.hero{break-after:page}}
  </style></head><body><main><header class="top"><span>Advantage Technologies</span><span>HIPAA Security Readiness Assessment Appendix</span></header><section class="hero"><span>${escapeHtml(period)}</span><h1>${escapeHtml(project.client.name)} HIPAA Security Readiness</h1><p>${escapeHtml(score.label)} · ${score.confirmedQuestionCount} of ${project.hipaa.answers.length} questions complete. This appendix preserves the question-level responses, optional notes, and any follow-up details behind the executive summary.</p></section><section class="score"><article><strong>${score.overall}%</strong><span>Overall readiness</span></article>${Object.entries(score.categories).map(([category,value])=>`<article><strong>${value}%</strong><span>${escapeHtml(category.replace(" Safeguards", ""))}</span></article>`).join("")}</section><div class="summary">Responses: ${score.counts.yes} Yes · ${score.counts.partially} Somewhat · ${score.counts.no} No · ${score.counts["not-applicable"]} Does not apply · ${score.counts["not-yet-assessed"]} Not sure / unanswered</div><div class="table-wrap"><table class="table"><thead><tr><th>Question</th><th>Question</th><th>Response</th><th>Optional notes / source</th><th>Client-visible observation</th><th>Recommended action</th></tr></thead><tbody>${rows}</tbody></table></div><div class="disclaimer">${escapeHtml(HIPAA_DISCLAIMER)}</div><footer class="footer"><span>Prepared by Advantage Technologies</span><span>${project.hipaa.clientConfirmation.status === "confirmed" ? `Confirmed by ${escapeHtml(project.hipaa.clientConfirmation.confirmer)}` : "Client confirmation pending"}</span></footer><div class="toolbar"><button onclick="window.print()">Print or save PDF</button></div></main></body></html>`;
}

export function downloadHipaaAppendixHtml(project: Project): void {
  const blob = new Blob([hipaaAppendixHtml(project)], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${safeFileName(project.client.name)}-hipaa-readiness-appendix.html`;
  anchor.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 1500);
}
