import type { HipaaQuestionDefinition } from "@/lib/projects/types";

export const HIPAA_QUESTION_SET_VERSION = "2026-quick-1";

/**
 * A short readiness conversation, not a substitute for a formal Security Rule risk analysis.
 * Related requirements are intentionally grouped so a small practice can answer the review
 * without completing a document-heavy, control-by-control audit inside the report builder.
 */
export const HIPAA_QUESTIONS: HipaaQuestionDefinition[] = [
  {
    id: "HIPAA-01",
    title: "Security leadership and written policies",
    category: "Administrative Safeguards",
    ownership: "client",
    question: "Is someone responsible for HIPAA security, and are written policies reviewed when the practice or its technology changes?",
    plainLanguageExplanation: "A name or role and a simple Yes, Somewhat, No, or Not sure answer are enough for this readiness review. Documentation can be discussed later when it is useful.",
    reviewPrompts: ["Who owns HIPAA security?", "When were policies last reviewed?"],
    clientConfirms: [], advantageConfirms: [], evidenceHints: [], notes: [], originalControlMapId: null,
    regulationMappings: ["45 CFR 164.308(a)(2)", "45 CFR 164.316"],
  },
  {
    id: "HIPAA-02",
    title: "Risk analysis and follow-through",
    category: "Administrative Safeguards",
    ownership: "client",
    question: "Has the practice completed a documented security risk analysis and tracked the risks that still need attention?",
    plainLanguageExplanation: "Confirm whether a current assessment exists and whether open risks have owners or next steps. The assessment itself does not need to be attached here.",
    reviewPrompts: ["Approximate date of the last risk analysis", "Are open risks being tracked?"],
    clientConfirms: [], advantageConfirms: [], evidenceHints: [], notes: [], originalControlMapId: null,
    regulationMappings: ["45 CFR 164.308(a)(1)(ii)(A)", "45 CFR 164.308(a)(1)(ii)(B)"],
  },
  {
    id: "HIPAA-03",
    title: "Workforce training and accountability",
    category: "Administrative Safeguards",
    ownership: "client",
    question: "Do team members receive security training, understand the rules, and know how violations are handled?",
    plainLanguageExplanation: "A quick description of the normal training process is enough. Training rosters or policy files are optional follow-up items.",
    reviewPrompts: ["New-hire and recurring training", "How policy violations are handled"],
    clientConfirms: [], advantageConfirms: [], evidenceHints: [], notes: [], originalControlMapId: null,
    regulationMappings: ["45 CFR 164.308(a)(3)", "45 CFR 164.308(a)(5)", "45 CFR 164.308(a)(1)(ii)(C)"],
  },
  {
    id: "HIPAA-04",
    title: "Access approval and offboarding",
    category: "Administrative Safeguards",
    ownership: "client",
    question: "Are user accounts approved by job role and promptly changed or removed when someone changes roles or leaves?",
    plainLanguageExplanation: "Think about the normal hiring, role-change, and termination process. A simple answer and an optional note are sufficient.",
    reviewPrompts: ["Who approves access?", "How quickly is access removed?"],
    clientConfirms: [], advantageConfirms: [], evidenceHints: [], notes: [], originalControlMapId: null,
    regulationMappings: ["45 CFR 164.308(a)(3)", "45 CFR 164.308(a)(4)", "45 CFR 164.312(a)(1)"],
  },
  {
    id: "HIPAA-05",
    title: "Business associates and vendor oversight",
    category: "Organizational Requirements",
    ownership: "client",
    question: "Are Business Associate Agreements in place with vendors that handle protected health information?",
    plainLanguageExplanation: "Answer based on the practice’s normal vendor process. A vendor list or copies of agreements are not required in this form.",
    reviewPrompts: ["Any known missing BAAs?", "How are vendors reviewed?"],
    clientConfirms: [], advantageConfirms: [], evidenceHints: [], notes: [], originalControlMapId: null,
    regulationMappings: ["45 CFR 164.308(b)", "45 CFR 164.314(a)"],
  },
  {
    id: "HIPAA-06",
    title: "Security incident response",
    category: "Administrative Safeguards",
    ownership: "client",
    question: "Do staff know how to report a suspected security incident, and is there a written response process?",
    plainLanguageExplanation: "The goal is to confirm that staff know whom to contact and that meaningful incidents are documented and followed through.",
    reviewPrompts: ["Who is contacted first?", "Where are incidents documented?"],
    clientConfirms: [], advantageConfirms: [], evidenceHints: [], notes: [], originalControlMapId: null,
    regulationMappings: ["45 CFR 164.308(a)(6)"],
  },
  {
    id: "HIPAA-07",
    title: "Contingency and disaster recovery",
    category: "Administrative Safeguards",
    ownership: "joint",
    question: "Are backup, disaster-recovery, and downtime plans documented and tested for critical systems?",
    plainLanguageExplanation: "The client confirms operational expectations while Advantage confirms the managed recovery capabilities it can see.",
    reviewPrompts: ["Critical systems", "Most recent recovery test", "How the practice works during downtime"],
    clientConfirms: ["Downtime and emergency process"], advantageConfirms: ["Backup monitoring and recovery capabilities"], evidenceHints: [], notes: [], originalControlMapId: null,
    regulationMappings: ["45 CFR 164.308(a)(7)"],
  },
  {
    id: "HIPAA-08",
    title: "Facilities, workstations, and device disposal",
    category: "Physical Safeguards",
    ownership: "joint",
    question: "Are work areas, mobile devices, and retired equipment protected from unauthorized access or improper disposal?",
    plainLanguageExplanation: "Consider screen visibility, unattended devices, portable equipment, storage areas, and how old hardware or media is wiped or destroyed.",
    reviewPrompts: ["Portable device safeguards", "Retired equipment process"],
    clientConfirms: ["Facility and workstation practices"], advantageConfirms: ["Managed-device inventory when available"], evidenceHints: [], notes: [], originalControlMapId: null,
    regulationMappings: ["45 CFR 164.310(a)", "45 CFR 164.310(b)", "45 CFR 164.310(c)", "45 CFR 164.310(d)"],
  },
  {
    id: "HIPAA-09",
    title: "Accounts, authentication, and secure exchange",
    category: "Technical Safeguards",
    ownership: "joint",
    question: "Do staff use individual accounts, multifactor authentication where appropriate, secure remote access, and secure methods for sending electronic protected health information?",
    plainLanguageExplanation: "Review the common systems and workflows rather than every account individually. Note any shared accounts or insecure transmission methods that need follow-up.",
    reviewPrompts: ["Shared accounts", "MFA coverage", "Remote access", "Secure email or file exchange"],
    clientConfirms: ["How staff access and exchange information"], advantageConfirms: ["Managed identity and remote-access controls"], evidenceHints: [], notes: [], originalControlMapId: null,
    regulationMappings: ["45 CFR 164.312(a)", "45 CFR 164.312(d)", "45 CFR 164.312(e)"],
  },
  {
    id: "HIPAA-10",
    title: "Periodic review and change management",
    category: "Administrative Safeguards",
    ownership: "joint",
    question: "Are security settings and policies reviewed when systems, vendors, locations, or workflows meaningfully change?",
    plainLanguageExplanation: "This is a quick check that security decisions do not become stale as the practice changes. Detailed change records are optional.",
    reviewPrompts: ["Last overall review", "Recent major technology or workflow changes"],
    clientConfirms: ["Operational and vendor changes"], advantageConfirms: ["Managed technology changes"], evidenceHints: [], notes: [], originalControlMapId: null,
    regulationMappings: ["45 CFR 164.308(a)(8)", "45 CFR 164.316"],
  },
  {
    id: "HIPAA-11",
    title: "Endpoint protection and security monitoring",
    category: "Technical Safeguards",
    ownership: "advantage-prefill",
    question: "Are managed computers protected and monitored, with meaningful security and system-activity alerts reviewed?",
    plainLanguageExplanation: "Advantage proposes this answer from imported managed-security evidence. The consultant only needs to confirm exceptions or uncovered systems.",
    reviewPrompts: ["Managed coverage", "Known exceptions"],
    clientConfirms: [], advantageConfirms: ["Endpoint protection", "Security monitoring", "Activity review"], evidenceHints: [], notes: [], originalControlMapId: null,
    regulationMappings: ["45 CFR 164.308(a)(1)(ii)(D)", "45 CFR 164.308(a)(5)", "45 CFR 164.312(b)"],
  },
  {
    id: "HIPAA-12",
    title: "Backup protection and recovery verification",
    category: "Technical Safeguards",
    ownership: "advantage-prefill",
    question: "Are backups for critical managed systems monitored and periodically tested for recovery?",
    plainLanguageExplanation: "Advantage proposes what can be confirmed from managed backup information. An identified Cloud Plus BDR emergency standby system supports this control, but its presence alone does not verify current backup health or recovery testing.",
    reviewPrompts: ["Cloud Plus BDR or managed backup coverage", "Most recent recovery test", "Systems outside Advantage scope"],
    clientConfirms: ["Critical systems outside managed scope"], advantageConfirms: ["Emergency standby coverage", "Local and cloud backup status", "Recovery testing"], evidenceHints: [], notes: [], originalControlMapId: null,
    regulationMappings: ["45 CFR 164.308(a)(7)", "45 CFR 164.310(d)(2)(iv)", "45 CFR 164.312(c)"],
  },
];

export function hipaaClientHandoffQuestions(): HipaaQuestionDefinition[] {
  return HIPAA_QUESTIONS.filter((question) => question.ownership !== "advantage-prefill");
}
